[build]
compiler = "gcc"

[[targets]]
name = "libheimdall-engine"
src = "engine"
include_dir = "engine/include"
type = 'dll'
cflags = " -g -Wall"
libs = "-lglew32 -lglfw3 -lopengl32 -lm"

[[targets]]
name = "testbed"
src = "testbed"
include_dir = "testbed/include"
type = "exe"
cflags = "-g -Wall"
libs = ""
deps = ["libheimdall-engine"]
