[build]
compiler = "gcc"

[[targets]]
name = "libheimdall-engine"
src = "engine"
include_dir = "engine/include"
type = 'dll'
cflags = " -g -Wall -Wextra `pkg-config --cflags freetype2`"
libs = "-lGLEW -lglfw `pkg-config --libs freetype2` -lm"

[[targets]]
name = "testbed"
src = "testbed"
include_dir = "testbed/include"
type = "exe"
cflags = "-g -Wall -Wextra"
libs = ""
deps = ["libheimdall-engine"]
